python train.py -m dmc_context_multi \
                      -d /workspace/shared/vimeo_septuplet \
                      -e 100 \
                      -lr 1e-5 \
                      -n 8 \
                      -q 3 \
                      --lambda 0.0067 \
                      --batch-size 8 \
                      --cuda \
                      --save \
                      --checkpoint /workspace/lm/NVC/checkpoints/dmc_context_multi/3/checkpoint_best_loss.pth.tar
