python train.py -m dmc \
                -d /workspace/shared/vimeo_septuplet \
                -e 200 \
                -lr 1e-4 \
                -n 8 \
                -q 6 \
                --lambda 2048 \
                --batch-size 8 \
                --max-frames 3 \
                --cuda \
                --save \
                --checkpoint /workspace/lm/videoCodec/dmc/checkpoints/dmc/2048.0/checkpoint.pth.tar
